### ISSUE TITLE
[BUG] Tech Reborn Quantum Armor Flight disallowed by PAL

### ISSUE THREAD

**Issue by james-ben** [AMPZNetwork/All-The-Fabric-5#3]
## Bug Description
The Tech Reborn Quantum Armor chest plate is supposed to allow creative flight.
There appears to be a conflict with PAL (PlayerAccessLib) which disallows this.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Acquire a Quantum Chestplate
2. Enter survival mode
3. Double tap space bar to try to fly
4. Check the console log

## Expected Outcome
The player is able to "double jump," as in jump on air, but is unable to have creative mode style flight, as expected ([wiki link](https://wiki.techreborn.ovh/doku.php?id=items:armor:quantum_armor))
The server doesn't crash, but instead spams the console with these errors causing huge log files.
The console spam can be mitigated by setting `alwaysLogTamperWarnings=false` in config/pal.properties
However, the issue of the Quantum Armor not allowing flight still remains.

## Related Issues
- https://github.com/TechReborn/TechReborn/issues/3176
- https://github.com/Ladysnake/PlayerAbilityLib/issues/16

## Error Log
```
[21/02/2024 09:40:31 AM] [Server thread/WARN] Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
[21/02/2024 09:40:31 AM] 	at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63)
[21/02/2024 09:40:31 AM] 	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_3222.handler$fif000$playerabilitylib$checkAbilityConsistency(class_3222.java:15424)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_3222.method_7355(class_3222.java:1323)
[21/02/2024 09:40:31 AM] 	at techreborn.items.armor.QuantumSuitItem.tickArmor(QuantumSuitItem.java:94)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_1657.handler$fnp00d$reborncore$tick(class_1657.java:21416)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_1657.method_5773(class_1657.java)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_3222.method_14226(class_3222.java:510)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_3244.method_18784(class_3244.java:269)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_2535.method_10754(class_2535.java:259)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_3242.method_14357(class_3242.java:172)
[21/02/2024 09:40:31 AM] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
[21/02/2024 09:40:31 AM] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
[21/02/2024 09:40:31 AM] 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
[21/02/2024 09:40:31 AM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
[21/02/2024 09:40:31 AM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[21/02/2024 09:40:31 AM] 	at java.base/java.lang.Thread.run(Thread.java:833)

```

## Basic Information (please fill in the following details):
 - Operating System: Windows 10
 - All The Fabric 5 Version: v5.5, 1.3.1
 - Additional Mods Installed: respawningshulkers-1.20.1-3.7, scaffoldingdropsnearby-1.20.1-3.2, shulkerdropstwo-1.20.1-3.3, starterkit-1.20.1-5.5, villagespawnpoint-1.20.1-4.2, welcomemessage-1.20.1-2.3, wits-1.1.0+1.20.1-fabric, YungsBetterNetherFortresses-1.20-Fabric-2.0.5, YungsBetterWitchHuts-1.20-Fabric-3.0.3

**Comment by LabsZero** [comment]
Your concern won't be a problem with patch 5.5. I suggest performing a fresh installation of the modpack (remember to backup your world and JourneyMap folder) before proceeding. If the issue persists, it's likely due to one of the mods you've added.
